package pers.hyu.tyche.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;
import pers.hyu.tyche.pojo.entity.UsersLikedVideos;
import pers.hyu.tyche.pojo.entity.UsersLikedVideosExample;

@Repository
public interface UsersLikedVideosMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_liked_videos
     *
     * @mbg.generated
     */
    long countByExample(UsersLikedVideosExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_liked_videos
     *
     * @mbg.generated
     */
    int deleteByExample(UsersLikedVideosExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_liked_videos
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_liked_videos
     *
     * @mbg.generated
     */
    int insert(UsersLikedVideos record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_liked_videos
     *
     * @mbg.generated
     */
    int insertSelective(UsersLikedVideos record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_liked_videos
     *
     * @mbg.generated
     */
    List<UsersLikedVideos> selectByExample(UsersLikedVideosExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_liked_videos
     *
     * @mbg.generated
     */
    UsersLikedVideos selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_liked_videos
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") UsersLikedVideos record, @Param("example") UsersLikedVideosExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_liked_videos
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") UsersLikedVideos record, @Param("example") UsersLikedVideosExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_liked_videos
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(UsersLikedVideos record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_liked_videos
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(UsersLikedVideos record);
}