package pers.hyu.tyche.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;
import pers.hyu.tyche.pojo.entity.UsersFollowers;
import pers.hyu.tyche.pojo.entity.UsersFollowersExample;

@Repository
public interface UsersFollowersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_followers
     *
     * @mbg.generated
     */
    long countByExample(UsersFollowersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_followers
     *
     * @mbg.generated
     */
    int deleteByExample(UsersFollowersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_followers
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_followers
     *
     * @mbg.generated
     */
    int insert(UsersFollowers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_followers
     *
     * @mbg.generated
     */
    int insertSelective(UsersFollowers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_followers
     *
     * @mbg.generated
     */
    List<UsersFollowers> selectByExample(UsersFollowersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_followers
     *
     * @mbg.generated
     */
    UsersFollowers selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_followers
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") UsersFollowers record, @Param("example") UsersFollowersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_followers
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") UsersFollowers record, @Param("example") UsersFollowersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_followers
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(UsersFollowers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_followers
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(UsersFollowers record);
}