package pers.hyu.tyche.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;
import pers.hyu.tyche.pojo.entity.VipVideoAccess;
import pers.hyu.tyche.pojo.entity.VipVideoAccessExample;

@Repository
public interface VipVideoAccessMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_video_access
     *
     * @mbg.generated
     */
    long countByExample(VipVideoAccessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_video_access
     *
     * @mbg.generated
     */
    int deleteByExample(VipVideoAccessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_video_access
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_video_access
     *
     * @mbg.generated
     */
    int insert(VipVideoAccess record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_video_access
     *
     * @mbg.generated
     */
    int insertSelective(VipVideoAccess record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_video_access
     *
     * @mbg.generated
     */
    List<VipVideoAccess> selectByExample(VipVideoAccessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_video_access
     *
     * @mbg.generated
     */
    VipVideoAccess selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_video_access
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") VipVideoAccess record, @Param("example") VipVideoAccessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_video_access
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") VipVideoAccess record, @Param("example") VipVideoAccessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_video_access
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(VipVideoAccess record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_video_access
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(VipVideoAccess record);
}