package pers.hyu.tyche.pojo.entity;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table comments
 */
public class Comments {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comments.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comments.parenet_comment_id
     *
     * @mbg.generated
     */
    private String parenetCommentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comments.to_user_id
     *
     * @mbg.generated
     */
    private String toUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comments.video_id
     *
     * @mbg.generated
     */
    private String videoId;

    /**
     * Database Column Remarks:
     *   the commenter
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comments.from_user_id
     *
     * @mbg.generated
     */
    private String fromUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comments.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comments.comment
     *
     * @mbg.generated
     */
    private String comment;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comments.id
     *
     * @return the value of comments.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comments.id
     *
     * @param id the value for comments.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comments.parenet_comment_id
     *
     * @return the value of comments.parenet_comment_id
     *
     * @mbg.generated
     */
    public String getParenetCommentId() {
        return parenetCommentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comments.parenet_comment_id
     *
     * @param parenetCommentId the value for comments.parenet_comment_id
     *
     * @mbg.generated
     */
    public void setParenetCommentId(String parenetCommentId) {
        this.parenetCommentId = parenetCommentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comments.to_user_id
     *
     * @return the value of comments.to_user_id
     *
     * @mbg.generated
     */
    public String getToUserId() {
        return toUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comments.to_user_id
     *
     * @param toUserId the value for comments.to_user_id
     *
     * @mbg.generated
     */
    public void setToUserId(String toUserId) {
        this.toUserId = toUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comments.video_id
     *
     * @return the value of comments.video_id
     *
     * @mbg.generated
     */
    public String getVideoId() {
        return videoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comments.video_id
     *
     * @param videoId the value for comments.video_id
     *
     * @mbg.generated
     */
    public void setVideoId(String videoId) {
        this.videoId = videoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comments.from_user_id
     *
     * @return the value of comments.from_user_id
     *
     * @mbg.generated
     */
    public String getFromUserId() {
        return fromUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comments.from_user_id
     *
     * @param fromUserId the value for comments.from_user_id
     *
     * @mbg.generated
     */
    public void setFromUserId(String fromUserId) {
        this.fromUserId = fromUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comments.create_time
     *
     * @return the value of comments.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comments.create_time
     *
     * @param createTime the value for comments.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comments.comment
     *
     * @return the value of comments.comment
     *
     * @mbg.generated
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comments.comment
     *
     * @param comment the value for comments.comment
     *
     * @mbg.generated
     */
    public void setComment(String comment) {
        this.comment = comment;
    }
}