package pers.hyu.tyche.pojo.entity;

import java.util.Date;

/**
 * Database Table Remarks:
 *   the table of record for the video searched
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table search_records
 */
public class SearchRecords {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column search_records.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     * Database Column Remarks:
     *   the content that need to be searched
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column search_records.content
     *
     * @mbg.generated
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column search_records.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column search_records.id
     *
     * @return the value of search_records.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column search_records.id
     *
     * @param id the value for search_records.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column search_records.content
     *
     * @return the value of search_records.content
     *
     * @mbg.generated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column search_records.content
     *
     * @param content the value for search_records.content
     *
     * @mbg.generated
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column search_records.create_time
     *
     * @return the value of search_records.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column search_records.create_time
     *
     * @param createTime the value for search_records.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}