package pers.hyu.tyche.pojo.entity;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table users_liked_videos
 */
public class UsersLikedVideos {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users_liked_videos.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users_liked_videos.user_id
     *
     * @mbg.generated
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users_liked_videos.video_id
     *
     * @mbg.generated
     */
    private String videoId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users_liked_videos.id
     *
     * @return the value of users_liked_videos.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users_liked_videos.id
     *
     * @param id the value for users_liked_videos.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users_liked_videos.user_id
     *
     * @return the value of users_liked_videos.user_id
     *
     * @mbg.generated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users_liked_videos.user_id
     *
     * @param userId the value for users_liked_videos.user_id
     *
     * @mbg.generated
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users_liked_videos.video_id
     *
     * @return the value of users_liked_videos.video_id
     *
     * @mbg.generated
     */
    public String getVideoId() {
        return videoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users_liked_videos.video_id
     *
     * @param videoId the value for users_liked_videos.video_id
     *
     * @mbg.generated
     */
    public void setVideoId(String videoId) {
        this.videoId = videoId;
    }
}