package pers.hyu.tyche.pojo.entity;

import java.util.ArrayList;
import java.util.List;

public class UsersExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table users
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table users
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table users
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbg.generated
     */
    public UsersExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table users
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("id like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("id not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andUsernameIsNull() {
            addCriterion("username is null");
            return (Criteria) this;
        }

        public Criteria andUsernameIsNotNull() {
            addCriterion("username is not null");
            return (Criteria) this;
        }

        public Criteria andUsernameEqualTo(String value) {
            addCriterion("username =", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameNotEqualTo(String value) {
            addCriterion("username <>", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameGreaterThan(String value) {
            addCriterion("username >", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameGreaterThanOrEqualTo(String value) {
            addCriterion("username >=", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameLessThan(String value) {
            addCriterion("username <", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameLessThanOrEqualTo(String value) {
            addCriterion("username <=", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameLike(String value) {
            addCriterion("username like", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameNotLike(String value) {
            addCriterion("username not like", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameIn(List<String> values) {
            addCriterion("username in", values, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameNotIn(List<String> values) {
            addCriterion("username not in", values, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameBetween(String value1, String value2) {
            addCriterion("username between", value1, value2, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameNotBetween(String value1, String value2) {
            addCriterion("username not between", value1, value2, "username");
            return (Criteria) this;
        }

        public Criteria andPasswordIsNull() {
            addCriterion("password is null");
            return (Criteria) this;
        }

        public Criteria andPasswordIsNotNull() {
            addCriterion("password is not null");
            return (Criteria) this;
        }

        public Criteria andPasswordEqualTo(String value) {
            addCriterion("password =", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotEqualTo(String value) {
            addCriterion("password <>", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordGreaterThan(String value) {
            addCriterion("password >", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordGreaterThanOrEqualTo(String value) {
            addCriterion("password >=", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordLessThan(String value) {
            addCriterion("password <", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordLessThanOrEqualTo(String value) {
            addCriterion("password <=", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordLike(String value) {
            addCriterion("password like", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotLike(String value) {
            addCriterion("password not like", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordIn(List<String> values) {
            addCriterion("password in", values, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotIn(List<String> values) {
            addCriterion("password not in", values, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordBetween(String value1, String value2) {
            addCriterion("password between", value1, value2, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotBetween(String value1, String value2) {
            addCriterion("password not between", value1, value2, "password");
            return (Criteria) this;
        }

        public Criteria andProfilePhotoIsNull() {
            addCriterion("profile_photo is null");
            return (Criteria) this;
        }

        public Criteria andProfilePhotoIsNotNull() {
            addCriterion("profile_photo is not null");
            return (Criteria) this;
        }

        public Criteria andProfilePhotoEqualTo(String value) {
            addCriterion("profile_photo =", value, "profilePhoto");
            return (Criteria) this;
        }

        public Criteria andProfilePhotoNotEqualTo(String value) {
            addCriterion("profile_photo <>", value, "profilePhoto");
            return (Criteria) this;
        }

        public Criteria andProfilePhotoGreaterThan(String value) {
            addCriterion("profile_photo >", value, "profilePhoto");
            return (Criteria) this;
        }

        public Criteria andProfilePhotoGreaterThanOrEqualTo(String value) {
            addCriterion("profile_photo >=", value, "profilePhoto");
            return (Criteria) this;
        }

        public Criteria andProfilePhotoLessThan(String value) {
            addCriterion("profile_photo <", value, "profilePhoto");
            return (Criteria) this;
        }

        public Criteria andProfilePhotoLessThanOrEqualTo(String value) {
            addCriterion("profile_photo <=", value, "profilePhoto");
            return (Criteria) this;
        }

        public Criteria andProfilePhotoLike(String value) {
            addCriterion("profile_photo like", value, "profilePhoto");
            return (Criteria) this;
        }

        public Criteria andProfilePhotoNotLike(String value) {
            addCriterion("profile_photo not like", value, "profilePhoto");
            return (Criteria) this;
        }

        public Criteria andProfilePhotoIn(List<String> values) {
            addCriterion("profile_photo in", values, "profilePhoto");
            return (Criteria) this;
        }

        public Criteria andProfilePhotoNotIn(List<String> values) {
            addCriterion("profile_photo not in", values, "profilePhoto");
            return (Criteria) this;
        }

        public Criteria andProfilePhotoBetween(String value1, String value2) {
            addCriterion("profile_photo between", value1, value2, "profilePhoto");
            return (Criteria) this;
        }

        public Criteria andProfilePhotoNotBetween(String value1, String value2) {
            addCriterion("profile_photo not between", value1, value2, "profilePhoto");
            return (Criteria) this;
        }

        public Criteria andNicknameIsNull() {
            addCriterion("nickname is null");
            return (Criteria) this;
        }

        public Criteria andNicknameIsNotNull() {
            addCriterion("nickname is not null");
            return (Criteria) this;
        }

        public Criteria andNicknameEqualTo(String value) {
            addCriterion("nickname =", value, "nickname");
            return (Criteria) this;
        }

        public Criteria andNicknameNotEqualTo(String value) {
            addCriterion("nickname <>", value, "nickname");
            return (Criteria) this;
        }

        public Criteria andNicknameGreaterThan(String value) {
            addCriterion("nickname >", value, "nickname");
            return (Criteria) this;
        }

        public Criteria andNicknameGreaterThanOrEqualTo(String value) {
            addCriterion("nickname >=", value, "nickname");
            return (Criteria) this;
        }

        public Criteria andNicknameLessThan(String value) {
            addCriterion("nickname <", value, "nickname");
            return (Criteria) this;
        }

        public Criteria andNicknameLessThanOrEqualTo(String value) {
            addCriterion("nickname <=", value, "nickname");
            return (Criteria) this;
        }

        public Criteria andNicknameLike(String value) {
            addCriterion("nickname like", value, "nickname");
            return (Criteria) this;
        }

        public Criteria andNicknameNotLike(String value) {
            addCriterion("nickname not like", value, "nickname");
            return (Criteria) this;
        }

        public Criteria andNicknameIn(List<String> values) {
            addCriterion("nickname in", values, "nickname");
            return (Criteria) this;
        }

        public Criteria andNicknameNotIn(List<String> values) {
            addCriterion("nickname not in", values, "nickname");
            return (Criteria) this;
        }

        public Criteria andNicknameBetween(String value1, String value2) {
            addCriterion("nickname between", value1, value2, "nickname");
            return (Criteria) this;
        }

        public Criteria andNicknameNotBetween(String value1, String value2) {
            addCriterion("nickname not between", value1, value2, "nickname");
            return (Criteria) this;
        }

        public Criteria andFollowerCountsIsNull() {
            addCriterion("follower_counts is null");
            return (Criteria) this;
        }

        public Criteria andFollowerCountsIsNotNull() {
            addCriterion("follower_counts is not null");
            return (Criteria) this;
        }

        public Criteria andFollowerCountsEqualTo(Integer value) {
            addCriterion("follower_counts =", value, "followerCounts");
            return (Criteria) this;
        }

        public Criteria andFollowerCountsNotEqualTo(Integer value) {
            addCriterion("follower_counts <>", value, "followerCounts");
            return (Criteria) this;
        }

        public Criteria andFollowerCountsGreaterThan(Integer value) {
            addCriterion("follower_counts >", value, "followerCounts");
            return (Criteria) this;
        }

        public Criteria andFollowerCountsGreaterThanOrEqualTo(Integer value) {
            addCriterion("follower_counts >=", value, "followerCounts");
            return (Criteria) this;
        }

        public Criteria andFollowerCountsLessThan(Integer value) {
            addCriterion("follower_counts <", value, "followerCounts");
            return (Criteria) this;
        }

        public Criteria andFollowerCountsLessThanOrEqualTo(Integer value) {
            addCriterion("follower_counts <=", value, "followerCounts");
            return (Criteria) this;
        }

        public Criteria andFollowerCountsIn(List<Integer> values) {
            addCriterion("follower_counts in", values, "followerCounts");
            return (Criteria) this;
        }

        public Criteria andFollowerCountsNotIn(List<Integer> values) {
            addCriterion("follower_counts not in", values, "followerCounts");
            return (Criteria) this;
        }

        public Criteria andFollowerCountsBetween(Integer value1, Integer value2) {
            addCriterion("follower_counts between", value1, value2, "followerCounts");
            return (Criteria) this;
        }

        public Criteria andFollowerCountsNotBetween(Integer value1, Integer value2) {
            addCriterion("follower_counts not between", value1, value2, "followerCounts");
            return (Criteria) this;
        }

        public Criteria andFollowCountsIsNull() {
            addCriterion("follow_counts is null");
            return (Criteria) this;
        }

        public Criteria andFollowCountsIsNotNull() {
            addCriterion("follow_counts is not null");
            return (Criteria) this;
        }

        public Criteria andFollowCountsEqualTo(Integer value) {
            addCriterion("follow_counts =", value, "followCounts");
            return (Criteria) this;
        }

        public Criteria andFollowCountsNotEqualTo(Integer value) {
            addCriterion("follow_counts <>", value, "followCounts");
            return (Criteria) this;
        }

        public Criteria andFollowCountsGreaterThan(Integer value) {
            addCriterion("follow_counts >", value, "followCounts");
            return (Criteria) this;
        }

        public Criteria andFollowCountsGreaterThanOrEqualTo(Integer value) {
            addCriterion("follow_counts >=", value, "followCounts");
            return (Criteria) this;
        }

        public Criteria andFollowCountsLessThan(Integer value) {
            addCriterion("follow_counts <", value, "followCounts");
            return (Criteria) this;
        }

        public Criteria andFollowCountsLessThanOrEqualTo(Integer value) {
            addCriterion("follow_counts <=", value, "followCounts");
            return (Criteria) this;
        }

        public Criteria andFollowCountsIn(List<Integer> values) {
            addCriterion("follow_counts in", values, "followCounts");
            return (Criteria) this;
        }

        public Criteria andFollowCountsNotIn(List<Integer> values) {
            addCriterion("follow_counts not in", values, "followCounts");
            return (Criteria) this;
        }

        public Criteria andFollowCountsBetween(Integer value1, Integer value2) {
            addCriterion("follow_counts between", value1, value2, "followCounts");
            return (Criteria) this;
        }

        public Criteria andFollowCountsNotBetween(Integer value1, Integer value2) {
            addCriterion("follow_counts not between", value1, value2, "followCounts");
            return (Criteria) this;
        }

        public Criteria andReceivedLikeCountsIsNull() {
            addCriterion("received_like_counts is null");
            return (Criteria) this;
        }

        public Criteria andReceivedLikeCountsIsNotNull() {
            addCriterion("received_like_counts is not null");
            return (Criteria) this;
        }

        public Criteria andReceivedLikeCountsEqualTo(Integer value) {
            addCriterion("received_like_counts =", value, "receivedLikeCounts");
            return (Criteria) this;
        }

        public Criteria andReceivedLikeCountsNotEqualTo(Integer value) {
            addCriterion("received_like_counts <>", value, "receivedLikeCounts");
            return (Criteria) this;
        }

        public Criteria andReceivedLikeCountsGreaterThan(Integer value) {
            addCriterion("received_like_counts >", value, "receivedLikeCounts");
            return (Criteria) this;
        }

        public Criteria andReceivedLikeCountsGreaterThanOrEqualTo(Integer value) {
            addCriterion("received_like_counts >=", value, "receivedLikeCounts");
            return (Criteria) this;
        }

        public Criteria andReceivedLikeCountsLessThan(Integer value) {
            addCriterion("received_like_counts <", value, "receivedLikeCounts");
            return (Criteria) this;
        }

        public Criteria andReceivedLikeCountsLessThanOrEqualTo(Integer value) {
            addCriterion("received_like_counts <=", value, "receivedLikeCounts");
            return (Criteria) this;
        }

        public Criteria andReceivedLikeCountsIn(List<Integer> values) {
            addCriterion("received_like_counts in", values, "receivedLikeCounts");
            return (Criteria) this;
        }

        public Criteria andReceivedLikeCountsNotIn(List<Integer> values) {
            addCriterion("received_like_counts not in", values, "receivedLikeCounts");
            return (Criteria) this;
        }

        public Criteria andReceivedLikeCountsBetween(Integer value1, Integer value2) {
            addCriterion("received_like_counts between", value1, value2, "receivedLikeCounts");
            return (Criteria) this;
        }

        public Criteria andReceivedLikeCountsNotBetween(Integer value1, Integer value2) {
            addCriterion("received_like_counts not between", value1, value2, "receivedLikeCounts");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(Integer value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(Integer value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(Integer value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(Integer value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(Integer value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<Integer> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<Integer> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(Integer value1, Integer value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andSecurityAnswerIsNull() {
            addCriterion("security_answer is null");
            return (Criteria) this;
        }

        public Criteria andSecurityAnswerIsNotNull() {
            addCriterion("security_answer is not null");
            return (Criteria) this;
        }

        public Criteria andSecurityAnswerEqualTo(String value) {
            addCriterion("security_answer =", value, "securityAnswer");
            return (Criteria) this;
        }

        public Criteria andSecurityAnswerNotEqualTo(String value) {
            addCriterion("security_answer <>", value, "securityAnswer");
            return (Criteria) this;
        }

        public Criteria andSecurityAnswerGreaterThan(String value) {
            addCriterion("security_answer >", value, "securityAnswer");
            return (Criteria) this;
        }

        public Criteria andSecurityAnswerGreaterThanOrEqualTo(String value) {
            addCriterion("security_answer >=", value, "securityAnswer");
            return (Criteria) this;
        }

        public Criteria andSecurityAnswerLessThan(String value) {
            addCriterion("security_answer <", value, "securityAnswer");
            return (Criteria) this;
        }

        public Criteria andSecurityAnswerLessThanOrEqualTo(String value) {
            addCriterion("security_answer <=", value, "securityAnswer");
            return (Criteria) this;
        }

        public Criteria andSecurityAnswerLike(String value) {
            addCriterion("security_answer like", value, "securityAnswer");
            return (Criteria) this;
        }

        public Criteria andSecurityAnswerNotLike(String value) {
            addCriterion("security_answer not like", value, "securityAnswer");
            return (Criteria) this;
        }

        public Criteria andSecurityAnswerIn(List<String> values) {
            addCriterion("security_answer in", values, "securityAnswer");
            return (Criteria) this;
        }

        public Criteria andSecurityAnswerNotIn(List<String> values) {
            addCriterion("security_answer not in", values, "securityAnswer");
            return (Criteria) this;
        }

        public Criteria andSecurityAnswerBetween(String value1, String value2) {
            addCriterion("security_answer between", value1, value2, "securityAnswer");
            return (Criteria) this;
        }

        public Criteria andSecurityAnswerNotBetween(String value1, String value2) {
            addCriterion("security_answer not between", value1, value2, "securityAnswer");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table users
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table users
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}