package pers.hyu.tyche.pojo.entity;

/**
 * Database Table Remarks:
 *   the relation table of the users and the followers
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table users_followers
 */
public class UsersFollowers {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users_followers.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     * Database Column Remarks:
     *   the user posted the videos
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users_followers.user_id
     *
     * @mbg.generated
     */
    private String userId;

    /**
     * Database Column Remarks:
     *   the follower
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users_followers.follower_id
     *
     * @mbg.generated
     */
    private String followerId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users_followers.id
     *
     * @return the value of users_followers.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users_followers.id
     *
     * @param id the value for users_followers.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users_followers.user_id
     *
     * @return the value of users_followers.user_id
     *
     * @mbg.generated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users_followers.user_id
     *
     * @param userId the value for users_followers.user_id
     *
     * @mbg.generated
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users_followers.follower_id
     *
     * @return the value of users_followers.follower_id
     *
     * @mbg.generated
     */
    public String getFollowerId() {
        return followerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users_followers.follower_id
     *
     * @param followerId the value for users_followers.follower_id
     *
     * @mbg.generated
     */
    public void setFollowerId(String followerId) {
        this.followerId = followerId;
    }
}