package pers.hyu.tyche.admin.pojo;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table videos
 */
public class Videos {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column videos.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     * Database Column Remarks:
     *   the user who upload the video
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column videos.user_id
     *
     * @mbg.generated
     */
    private String userId;

    /**
     * Database Column Remarks:
     *   the background music that added by the user
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column videos.bmg_id
     *
     * @mbg.generated
     */
    private String bmgId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column videos.video_desc
     *
     * @mbg.generated
     */
    private String videoDesc;

    /**
     * Database Column Remarks:
     *   the path of the video stored
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column videos.video_path
     *
     * @mbg.generated
     */
    private String videoPath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column videos.video_seconds
     *
     * @mbg.generated
     */
    private Float videoSeconds;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column videos.video_width
     *
     * @mbg.generated
     */
    private Integer videoWidth;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column videos.video_height
     *
     * @mbg.generated
     */
    private Integer videoHeight;

    /**
     * Database Column Remarks:
     *   the path of the cover of the video
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column videos.cover_path
     *
     * @mbg.generated
     */
    private String coverPath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column videos.like_counts
     *
     * @mbg.generated
     */
    private Integer likeCounts;

    /**
     * Database Column Remarks:
     *   the status of the video: -1、forbidden, 0、active, 1 for vip_video that only vip user can access
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column videos.status
     *
     * @mbg.generated
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column videos.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column videos.id
     *
     * @return the value of videos.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column videos.id
     *
     * @param id the value for videos.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column videos.user_id
     *
     * @return the value of videos.user_id
     *
     * @mbg.generated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column videos.user_id
     *
     * @param userId the value for videos.user_id
     *
     * @mbg.generated
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column videos.bmg_id
     *
     * @return the value of videos.bmg_id
     *
     * @mbg.generated
     */
    public String getBmgId() {
        return bmgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column videos.bmg_id
     *
     * @param bmgId the value for videos.bmg_id
     *
     * @mbg.generated
     */
    public void setBmgId(String bmgId) {
        this.bmgId = bmgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column videos.video_desc
     *
     * @return the value of videos.video_desc
     *
     * @mbg.generated
     */
    public String getVideoDesc() {
        return videoDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column videos.video_desc
     *
     * @param videoDesc the value for videos.video_desc
     *
     * @mbg.generated
     */
    public void setVideoDesc(String videoDesc) {
        this.videoDesc = videoDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column videos.video_path
     *
     * @return the value of videos.video_path
     *
     * @mbg.generated
     */
    public String getVideoPath() {
        return videoPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column videos.video_path
     *
     * @param videoPath the value for videos.video_path
     *
     * @mbg.generated
     */
    public void setVideoPath(String videoPath) {
        this.videoPath = videoPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column videos.video_seconds
     *
     * @return the value of videos.video_seconds
     *
     * @mbg.generated
     */
    public Float getVideoSeconds() {
        return videoSeconds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column videos.video_seconds
     *
     * @param videoSeconds the value for videos.video_seconds
     *
     * @mbg.generated
     */
    public void setVideoSeconds(Float videoSeconds) {
        this.videoSeconds = videoSeconds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column videos.video_width
     *
     * @return the value of videos.video_width
     *
     * @mbg.generated
     */
    public Integer getVideoWidth() {
        return videoWidth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column videos.video_width
     *
     * @param videoWidth the value for videos.video_width
     *
     * @mbg.generated
     */
    public void setVideoWidth(Integer videoWidth) {
        this.videoWidth = videoWidth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column videos.video_height
     *
     * @return the value of videos.video_height
     *
     * @mbg.generated
     */
    public Integer getVideoHeight() {
        return videoHeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column videos.video_height
     *
     * @param videoHeight the value for videos.video_height
     *
     * @mbg.generated
     */
    public void setVideoHeight(Integer videoHeight) {
        this.videoHeight = videoHeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column videos.cover_path
     *
     * @return the value of videos.cover_path
     *
     * @mbg.generated
     */
    public String getCoverPath() {
        return coverPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column videos.cover_path
     *
     * @param coverPath the value for videos.cover_path
     *
     * @mbg.generated
     */
    public void setCoverPath(String coverPath) {
        this.coverPath = coverPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column videos.like_counts
     *
     * @return the value of videos.like_counts
     *
     * @mbg.generated
     */
    public Integer getLikeCounts() {
        return likeCounts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column videos.like_counts
     *
     * @param likeCounts the value for videos.like_counts
     *
     * @mbg.generated
     */
    public void setLikeCounts(Integer likeCounts) {
        this.likeCounts = likeCounts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column videos.status
     *
     * @return the value of videos.status
     *
     * @mbg.generated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column videos.status
     *
     * @param status the value for videos.status
     *
     * @mbg.generated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column videos.create_time
     *
     * @return the value of videos.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column videos.create_time
     *
     * @param createTime the value for videos.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}