
######################################################
#
# Service related configuration
#
######################################################
server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8
debug: false


######################################################
#
# Log related configuration
#
######################################################
logging:
  level:
    root: info
    org:
      springframework:
        security: warn
        web: info
      mybatis: warn
#  pattern:
#    console: '%d{yyyy-MMM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{15} - %msg%n'

######################################################
#
# DataSource configuration
#
######################################################
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/tyche
    username: root
    password: password
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      pool-name: TycheHikarCP
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 28740000
      connection-test-query: SELECT 1

  # file upload config
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  ######################################################
  #
  # Redis configuration
  #
  ######################################################
  redis:
    database: 1
    host: 192.168.0.111
    port: 6379
    password: password
    jedis:
      pool:
        max-active: 1000
        max-wait: -1
        max-idle: 10
        min-idle: 2
    timeout: 0


######################################################
#
# Mybatis configuration
#
######################################################
mybatis:
  type-aliases-package: pers.hyu.pojo.entity
  mapper-locations: classpath:mapper/*.xml
# Mapper config
#mapper:
##  mappers: pers.hyu.utils.MyMapper
#  not-empty: false
#  identity: MARIADB

# Pagehelper config
pagehelper:
  #  dialect: mariadb
  support-methods-arguments: true
  params: count=countSql
  reasonable: true
  limit: 6
  comments-limit: 10



######################################################
#
# other configuration
#
######################################################

vip-pass: "Yu Yufei"
file-space: "c:/tyche"
ffmpeg-exe: "c:/tyche/ffmpeg-4.3.1/bin/ffmpeg.exe"
bgm-server: "http://192.168.0.17:8081/bgm_admin"

default-hotSearch:
  topNum: 5
  default_1: "niuniu"
  default_2: "yufei"
  default_3: "xiaojinyu"

zookeeper:
  server: 192.168.0.111:2181
  retry-policy:
    waiting: 1000
    connect: 5
  client:
    session-timeout: 10000
    connection-timeout: 10000
  name-space: admin
  node-path: "/bgm"





